"""
tello_control.core.backend

Der *Vertrag*, den jedes Backend (mock, sim, real) erfüllt. Bisher war die
Backend-Austauschbarkeit nur eine Konvention — ``DroneController`` rief Methoden
auf und hoffte, dass alle drei sie besitzen. Diese Protokolle machen den Vertrag
explizit und statisch prüfbar (mypy), ohne zur Laufzeit etwas zu erzwingen:

* ``DroneBackend`` — die Schnittmenge, die alle drei können. ``djitellopy.Tello``
  erfüllt sie *strukturell* (Duck-Typing), ganz ohne Import oder Vererbung hier.
* ``PoseBackend`` — zusätzlich die simulierte Pose-Führung, die nur Mock und Sim
  bieten (die echte Drohne kennt ihre Position nicht). ``position()``/``report()``/
  ``tick()`` im Controller sind genau auf diese Backends beschränkt.

Beide sind ``runtime_checkable``, damit der Controller mit ``isinstance`` sauber
zwischen "kann Pose" und "kann nicht" unterscheidet, statt an interne Felder zu
greifen.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class DroneBackend(Protocol):
    """Gemeinsame Oberfläche von Mock, Sim und echter Tello.

    ``DroneController`` spricht ausschließlich mit dieser Schnittstelle, darum
    sind die drei Backends hinter einem einzigen Argument austauschbar.
    """

    def connect(self) -> None: ...
    def get_battery(self) -> int: ...
    def get_height(self) -> int: ...

    def takeoff(self) -> None: ...
    def land(self) -> None: ...
    def emergency(self) -> None: ...

    def move_forward(self, cm: int) -> None: ...
    def move_back(self, cm: int) -> None: ...
    def move_left(self, cm: int) -> None: ...
    def move_right(self, cm: int) -> None: ...
    def move_up(self, cm: int) -> None: ...
    def move_down(self, cm: int) -> None: ...
    def rotate_clockwise(self, deg: int) -> None: ...
    def rotate_counter_clockwise(self, deg: int) -> None: ...

    def send_rc_control(self, lr: int, fb: int, ud: int, yaw: int) -> None: ...
    def end(self) -> None: ...


@runtime_checkable
class PoseBackend(DroneBackend, Protocol):
    """Ein Backend, das zusätzlich eine simulierte Pose mitführt (mock + sim).

    Bietet Pose-Integration und Auswertung, die die echte Drohne nicht liefern
    kann — deshalb sind ``position()``/``report()`` im Controller darauf begrenzt.
    """

    def tick(self, dt: float | None = ...) -> None: ...
    def pose(self) -> tuple[float, float, float, float]: ...
    def print_log(self) -> None: ...
    def print_map(self) -> None: ...
